#!/bin/bash
# Matterformer good-run parity architecture with Muon and Triton radial-r2 attention bias.

#SBATCH --partition=all6000
#SBATCH --account=all6000users
#SBATCH --gres=gpu:1
#SBATCH --job-name=mf_good_r2_muon
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=16
#SBATCH --time=5-00:00:00
#SBATCH --mem=96G
#SBATCH --output=/home/thadziv/matterformer_jobs/job_outputs/slurm_output_%A_mf_good_r2_muon.out

set -euo pipefail

REPO_ROOT="${REPO_ROOT:-/home/thadziv/GitHub/Matterformer}"

export HYBRID_CONFIG_JSON="${HYBRID_CONFIG_JSON:-$REPO_ROOT/configs/omol/tetra_t_only_h1920_l16_pt2_goodrun_qkn_uk_csfilm_radialr2.json}"
export MODEL_BACKEND="${MODEL_BACKEND:-matterformer}"
export OMOL_RUNTIME_MODE="${OMOL_RUNTIME_MODE:-internal_flat_tetra}"

export D_MODEL="${D_MODEL:-1920}"
export N_HEADS="${N_HEADS:-12}"
export N_LAYERS="${N_LAYERS:-16}"
export MLP_RATIO="${MLP_RATIO:-4.0}"
export DROPOUT="${DROPOUT:-0.0}"
export ATTN_DROPOUT="${ATTN_DROPOUT:-0.0}"
export CHGSPIN_MODE="${CHGSPIN_MODE:-add}"
export CHGSPIN_EMB_DIM="${CHGSPIN_EMB_DIM:-160}"
export READOUT_HEAD_MODE="${READOUT_HEAD_MODE:-platonic}"
export READOUT_ACTIVATION="${READOUT_ACTIVATION:-gelu}"

export BATCH_SIZE="${BATCH_SIZE:-16}"
export VAL_BATCH_SIZE="${VAL_BATCH_SIZE:-16}"
export MAX_GRAPHS_PER_BATCH="${MAX_GRAPHS_PER_BATCH:-999999}"
export MAX_GRAPHS_PER_BATCH_VAL="${MAX_GRAPHS_PER_BATCH_VAL:-999999}"
export MAX_ATOMS_PER_BATCH="${MAX_ATOMS_PER_BATCH:-12000}"
export MAX_ATOMS_PER_BATCH_VAL="${MAX_ATOMS_PER_BATCH_VAL:-12000}"
export MAX_EDGES_PER_BATCH="${MAX_EDGES_PER_BATCH:-2400000}"
export MAX_EDGES_PER_BATCH_VAL="${MAX_EDGES_PER_BATCH_VAL:-2400000}"
export NUM_WORKERS="${NUM_WORKERS:-16}"
export PREFETCH_FACTOR="${PREFETCH_FACTOR:-4}"
export PIN_MEMORY="${PIN_MEMORY:-1}"
export BATCHING_MODE="${BATCHING_MODE:-random}"
export BUCKET_WINDOW_SIZE="${BUCKET_WINDOW_SIZE:-4096}"
export BUCKET_SHUFFLE_GROUPS="${BUCKET_SHUFFLE_GROUPS:-8}"
export VALIDATION_MODE="${VALIDATION_MODE:-heldout}"

export MAX_EPOCHS="${MAX_EPOCHS:-20}"
export MAX_STEPS="${MAX_STEPS:-0}"
export LR="${LR:-5e-4}"
export LR_MIN="${LR_MIN:-1e-6}"
export WEIGHT_DECAY="${WEIGHT_DECAY:-1e-8}"
export WARMUP_STEPS="${WARMUP_STEPS:-2000}"
export NORMALIZER_RMSD="${NORMALIZER_RMSD:-1.433569}"
export ENERGY_WEIGHT="${ENERGY_WEIGHT:-10}"
export FORCE_WEIGHT="${FORCE_WEIGHT:-20}"
export ENERGY_LOSS="${ENERGY_LOSS:-per_atom_mae}"
export FORCE_LOSS="${FORCE_LOSS:-l2norm}"
export TRAIN_AUGMENTATION="${TRAIN_AUGMENTATION:-o3}"
export GRAD_CLIP_NORM="${GRAD_CLIP_NORM:-1}"
export SKIP_LOSS_ABOVE="${SKIP_LOSS_ABOVE:-1000}"
export EMA_DECAY="${EMA_DECAY:-0.99}"
export EMA_WARMUP_STEPS="${EMA_WARMUP_STEPS:-2000}"
export BF16="${BF16:-0}"
export FLOAT32_MATMUL_PRECISION="${FLOAT32_MATMUL_PRECISION:-high}"
export COMPILE="${COMPILE:-1}"
export COMPILE_MODE="${COMPILE_MODE:-default}"
export COMPILE_SCOPE="${COMPILE_SCOPE:-trunk_flat}"
export MATTERFORMER_PLATONIC_TRITON_BWD="${MATTERFORMER_PLATONIC_TRITON_BWD:-auto}"
export MATTERFORMER_PLATONIC_TRITON_DELTA="${MATTERFORMER_PLATONIC_TRITON_DELTA:-triton_vector}"
export MATTERFORMER_PLATONIC_TRITON_SPLIT_HEAD_DIM="${MATTERFORMER_PLATONIC_TRITON_SPLIT_HEAD_DIM:-auto}"
export MATTERFORMER_PLATONIC_TRITON_FWD_NUM_STAGES="${MATTERFORMER_PLATONIC_TRITON_FWD_NUM_STAGES:-3}"
export MATTERFORMER_PLATONIC_TRITON_BWD_NUM_STAGES="${MATTERFORMER_PLATONIC_TRITON_BWD_NUM_STAGES:-1}"
export TETRA_ATTENTION_BLOCK_M="${TETRA_ATTENTION_BLOCK_M:-16}"
export TETRA_ATTENTION_BLOCK_N="${TETRA_ATTENTION_BLOCK_N:-32}"

export OPTIMIZER="${OPTIMIZER:-muon}"
export MUON_LR="${MUON_LR:-0.02}"
export MUON_MOMENTUM="${MUON_MOMENTUM:-0.95}"
export MUON_WEIGHT_DECAY="${MUON_WEIGHT_DECAY:-0}"
export MUON_ADAM_LR="${MUON_ADAM_LR:-5e-4}"
export MUON_ADAM_WEIGHT_DECAY="${MUON_ADAM_WEIGHT_DECAY:-1e-8}"
export MUON_ADAM_BETA1="${MUON_ADAM_BETA1:-0.9}"
export MUON_ADAM_BETA2="${MUON_ADAM_BETA2:-0.999}"
export MUON_ADAM_EPS="${MUON_ADAM_EPS:-1e-8}"
export MUON_HIDDEN_ONLY="${MUON_HIDDEN_ONLY:-1}"
export MUON_MIN_NDIM="${MUON_MIN_NDIM:-2}"
export MUON_PLATONIC_KERNEL_VIEW="${MUON_PLATONIC_KERNEL_VIEW:-conv}"
export MUON_EXCLUDE_NAME_FRAGMENTS="${MUON_EXCLUDE_NAME_FRAGMENTS:-embed,embedding,head,readout,rope,freq,attn.}"

export FLOPS_COEF="${FLOPS_COEF:-72}"
export FULL_VAL_EVERY_STEPS="${FULL_VAL_EVERY_STEPS:-5000}"
export LIMIT_VAL_BATCHES="${LIMIT_VAL_BATCHES:-500}"
export LIMIT_TEST_BATCHES="${LIMIT_TEST_BATCHES:-500}"
export VAL_ESTIMATE_EVERY_STEPS="${VAL_ESTIMATE_EVERY_STEPS:-0}"
export VAL_ESTIMATE_BATCHES="${VAL_ESTIMATE_BATCHES:-16}"
export PROFILE_STEPS="${PROFILE_STEPS:-0}"
export PROFILE_WARMUP_STEPS="${PROFILE_WARMUP_STEPS:-5}"

export RUN_SLUG="${RUN_SLUG:-matterformer-pt2-h1920-l16-ls1e-4-ffn4-actsin-ractgelu-rs2.0-qkn-uk-csFiLM-radialr2-splitDauto-bm16bn32-ema0.99-wd1e-8-lr5e-4-lrmin1e-6-muonffnconv0.02-mwd0-warm2k-auxadamw-fw20-20ep-n12000-flat-maxg999999-platonichead-trunkcompile-skip1000}"
export WANDB_PROJECT="${WANDB_PROJECT:-matterformer_omol_4m}"
export WANDB_GROUP="${WANDB_GROUP:-matterformer_pt2_l16_goodrun_qkn_uk_csfilm_radialr2_splitDauto_muon_warm2k_fw20_n12000}"

exec "$REPO_ROOT/scripts/omol_forcefield_delta.sh"
